repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: python -m black src  # Command to be executed
    language: system
    types: [python]
  
  - id: isort
    name: isort
    entry: python -m isort src
    language: system
    types: [python]

  - id: flake8
    name: flake8
    entry: python -m flake8 src --config=setup.cfg # Command to be executed
    language: system
    types: [python]

  - id: pyright
    name: pyright
    entry: python -m pyright src # Command to be executed
    language: system
    types: [python]
